source "https://rubygems.org"

gem 'coveralls', require: false
gem 'rspec'
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in etiqueta.gemspec
gemspec
